UKHomeOffice/cop-private-workflow-tasklist

public/styles/app.scss
The gov.uk styles assume that the govuk-details element is outside the form-group so the bottom margin of the form-group adds spacing between the two elements.
Our forms have the govuk-details element inside the form-group so we need to add top margin to the govuk-details element to add spacing between it and the field.
**From this**
**To this**
=> Add top margin to form tooltips

public/styles/app.scss
The main body with is controlled by bootstrap classes so we need to override the widest one so it's the same width as the gds template
before
after
=> Reduce the width of the main body to make it the same size as the gds header

app/index.js
This is needed for environments where `NODE_ENV !== 'production'`
=> Add missing env vars to appConfig

public/styles/app.scss
Remove service name indentation so it aligns with the left side of the app, because properly aligned elements are a wonderful thing ;)
Before:
After:
=> Remove service name indentation

app/core/util/GovUKFrontEndObserver.js, app/core/util/GovUKFrontEndObserver.test.js
Can't really test the internal MutationObserver here, but this does give 100% coverage of the GovUKFrontEndObserver instance.
=> Add test coverage for observer

public/styles/app.scss
After discussion with Richard, we think it is best if we deploy this CSS as an interim fix for OAR and I have created a new ticket (PC-81) for a more major DataGrid component re-write to occur at a later date.
In the meantime, this CSS does not seem to break any existing DataGrids and if new ones are built using a couple of additional containers and classes (see OAR for an example) then they are much more responsive.
=> CSS to support interim responsive DataGrid structure

app/pages/task/form/components/TaskForm.jsx
_For review once code freeze is over._
This makes the Submit button say "Submit" for all tasks. It still has different text for shift starting/editing.
I'm not exactly sure of how the i18n options are leaking out of the `ShiftForm.jsx` and into the `TaskForm.jsx`, but explicitly setting config here fixes the issue. This may affect all forms, but I believe all tasks should say "Submit" anyway.
=> Fix submit button text for ManDec task

app/pages/shift/components/ShiftForm.jsx
This sets the Shift Form submit button text to be "Submit" for both starting and amending a shift.
=> Change Shift Form submit button text

app/pages/task/display/component/Attachments.jsx
This PR updates the `Attachments` component to a stateless component, and lints module.
Run linter (this command runs linter for the Attachments module only):
```
npm run linter:dev -- app/pages/task/display/component/Attachments.jsx
```
=> Update attachments component

.eslintrc.json, app/pages/task/display/component/Claim.jsx
This PR updates the `Claim` component to be a stateless component, adds props validation and lints the module.
Run linter (this command runs linter for the Claim module only):
npm run linter:dev -- app/pages/task/display/component/Claim.jsx
=> Update claim component

app/pages/task/display/component/Actions.jsx
Hide actions tooltip for Man Dec review tasks because we only have the `Claim` button so the text above the button is descriptive enough.
I've not fixed additional linting for this file because it breaks the page so this will require additional work that we don't need to include in the Man Dec release
=> CO-962 - Hide Tooltip in Claim task for first and second reviews

app/core/Main.jsx
This PR redirects users that have already onboarded and started the shift to the dashboard page. This means that any user that has already onboarded and tries to access the `/on-board` url will be redirected to the dashboard.
If the user has onboarded but not started the shift the user will be redirected to the start shift page.
=> Redirect onboarded to dashboard

app/core/Main.jsx
This PR ensures that `ProcessStartPage` does not call a nested onboarding and shift check.
=> Removes circular check

public/styles/app.scss
I looked at preventing the scrollbar too, but this will need a bit more attention as viewport height units look different on mobile vs desktop. Scrollbar still shows here with no iframe border. This is the only iframe in the app so far.
=> Show no border for any iframes

.eslintrc.json, app/pages/task/display/component/Actions.jsx, app/pages/task/display/component/Claim.jsx, app/pages/task/display/component/TaskSummaryPage.jsx
This PR updates the Actions component to be a stateless component, adds props validation and lints the module.
Run linter (this command runs linter for the Actions module only):
```
npm run linter:dev -- app/pages/task/display/component/Actions.jsx
```
Currently linter reports one error for this module, this will be fixed once the module `Complete` is linted in a different PR
=> Update actions component

webpack.dev.js
Necessary for VM connection as it is a domain expected by KC/CORS.
=> Allow lodev for WDS

app/pages/shift/components/ShiftForm.jsx
To pre-populate the `shift` form we're mapping the values returned from the db to the form fields in `ShiftForm`.
This change adds a mapping for `defaultteam` in the `staff` record to `team` in the shift form in order to pre-populate the `team` field.
=> CO-1258 - Add defaultteam to the shift data

app/pages/shift/components/ShiftForm.jsx
Convert the default team back to an object before it's used to pre-populate the team field in the shift form as staffDetails is immutable.
=> Convert the default team back to an object

.drone.yml
Multiple lines in a commit comment is coming through as a map, not a string
=> CB-1276 Use commit sha instead of commit message

app/pages/task/form/components/TaskForm.jsx
On the Man Dec first and second review forms we add `submissionData` as a process variable with the positive declaration data that the job holder has entered so it can be displayed back to the reviewers.
We also add the process variables to the payload as `processContext` so that data can be accessed across different forms in the same process.
Because Man Dec has several forms and a lot of data, we're getting a data recursion issue where the Make Your Declaration form can't be re-submitted after the declaration has been rejected at the first review. This is because the data gets deeply nested after adding the `submissionData` and `processContext` data for each form in the process.
This PR fixes that by removing the `submissionData` from the process after it has been used for displaying …
=>  Remove submissionData from process variables before adding to the payload

app/pages/forms/start/components/StartForm.jsx
We want to save the user roles to Keycloak rather than the database and to do that we need the Keycloak user id in the executor to build the request url for adding the roles.
This change adds `subject`, which is the value returned from Keycloak with the user id, to `keycloakContext` which is available during the rendering of the form and removed before submission.
There will be a new hidden field added to the onboard user form which will get this Keycloak user id and add it to the payload to make it available in the executor.
=> CO-1527 - Add subject to the keycloakContext

.drone.yml, app/core/util/browserIsSupported.js, app/core/util/browserIsSupported.test.js, app/index.jsx, env.yaml, kube/deployment.yml, webpack.dev.js
• If `DETECT_BROWSER` is not defined, or set as anything other than 'true', then `BROWSER_CONFIG` may or may not be defined - there is no detection.
• If `DETECT_BROWSER` is defined and set as 'true', then `BROWSER_CONFIG` must also be defined (in the expected format).
=> Set browser detection to be env-var-driven

package-lock.json
This is a measure to avoid a problem introduced in later versions whereby disabled fields cannot be validated. When this is remedied by Formio we could delete and rebuild the lock file.
=> Use package-lock file to pin Formiojs to 4.9.5

app/pages/forms/start/components/StartForm.jsx
We're using roles from Keycloak rather than than the db and so we need to change the Assign a Role form to fetch the roles from Keycloak.
In order to do this we need to add `url` and `realm` to `keycloakContext` in `StartForm` to they can be used in the form to make the API request to Keycloak.
=> Add url and realm to keycloakContext in StartForm

app/core/util/browserIsSupported.js, app/core/util/browserIsSupported.test.js
The existing code hasn't so far caused any issues in production, but when browser versions exceed 99 it would, the reason being that strings are compared lexographically. This PR casts one side as a number, which is sufficient for JavaScript to perform automatic type conversion and compare both sides numerically. I've updated a test to be a scenario that would fail without this measure.
In the second commit I add tests to confirm that the code works as expected (i.e. is permissive) when minor version is omitted from the config.
=> Enhance browser detection

app/core/util/browserIsSupported.test.js
We're going to block Internet Explorer via env var as well, so here we say we will not allow in any version of this browser lower than 99. Also some auto-formatting.
=> Amend a couple of tests to use IE instead

app/core/util/browserIsSupported.js, app/core/util/browserIsSupported.test.js
• Move from regex to strict identity string match for browser name
• Change name/browser separator to be colon rather than hyphen
• Add chromium-webview user agent string for tests
• Tweak logic to ensure unmentioned browsers are always admitted
This is a breaking change for the current env var structure. In other words, when this is deployed to a given env, that env must at the same time either have `DETECT_BROWSER` set to `false` or have its `BROWSER_VERSIONS` set as colon delimited - i.e.  `chrome:64.0,edge:17.17134,ie:99,chromium-webview:64.0`. I'll co-ordinate this with Dev Ops.
=> Enable detection for chromium-webview

.prettierrc, app/core/Main.jsx, app/pages/reports/components/HTMLReport.jsx, app/pages/reports/components/HTMLReport.test.jsx, app/pages/reports/components/PowerBIReport.jsx, app/pages/reports/components/PowerBIReport.test.jsx, app/pages/reports/components/ReportPage.jsx, app/pages/reports/components/ReportPage.test.jsx, app/pages/reports/components/ReportsPage.jsx, app/pages/reports/components/ReportsPage.test.jsx, app/pages/reports/components/__snapshots__/HTMLReport.test.jsx.snap, app/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap, app/pages/reports/components/__snapshots__/ReportPage.test.jsx.snap, app/pages/reports/components/__snapshots__/ReportsPage.test.jsx.snap, app/pages/reports/reducer.js, jestsetup.js, package-lock.json, package.json
Here we receive an array of reports, as before, but we use a different component and props depending on whether the report is Power BI or custom HTML.
The reports are viewable using a new dynamic route, but we do not expose properties such as the embed token over the URL (instead we use the history object) - the reports are not supposed to be viewable over a hyperlink, but rather must be viewed via a click.
We do not cache responses in the end, because this may introduce additional complications re. authentication, and we found speed to be perfectly adequate.
=> Support viewing of Power BI reports in UI

webpack.prod.js
This ticket relates to removing console warnings visible in production. Most were warnings related to `moment` and I'm not able to see any of those now (I think they've been "upgraded away"), leaving only the Keycloak info messages also mentioned in the ticket.
I don't think there should be a need for console logs in production, so strip them in the Webpack build here. I'm noting on the ticket which forms I have checked and that any further warnings we notice can and should be dealt with in Dev.
=> Remove console messages from prod build

app/core/components/NotFound.jsx, app/core/components/NotFound.test.jsx, app/core/components/__snapshots__/NotFound.test.jsx.snap, app/core/error/component/ErrorHandlingComponent.jsx, app/pages/forms/start/components/FormsStartPage.test.jsx, app/pages/tasks/components/YourGroupTasks.test.jsx, app/pages/tasks/components/YourTasks.test.jsx
This handles 404 errors and instead of showing error notices in this case shows a more user-friendly 404 page. (Also some adding of props for tests and linting.)
=> Add 404 page for when forms are not found

public/index.html, webpack.common.js
Many thanks to @shepda for spotting the probable underlying issue here (favicons needing to be copied into the `dist` dir on build and referenced there!). We'll try this in browsers on Dev.
=> Copy favicon images to dist and reference in index.html

app/pages/forms/start/components/FormsStartPage.jsx
This is for a request from Richard that the user be able to cancel specifically when on the User Profile form. When a `cancel-form` event is dispatched from a form, we'll return the user to the forms list page. Also a couple of linting fixes in here.
=> Enable custom event for form cancellation

public/styles/app.scss
AC: line breaks in _details_ textareas need to be retained so when we display them back it's not one blob of text
To test:
- submit an Intelligence Referral form, make sure for details you enter multiple paragraphs with line breaks
- view the case
- view the intel report within the case 
- go to the details section
- you should see the text as you typed it originally, with line breaks
=> Add css to preserve linebreaks in textareas

app/common/AppConstants.js, app/core/components/Header.jsx, app/core/components/Header.scss, app/core/components/Header.test.js, app/core/components/__snapshots__/Header.test.js.snap
**AC**
- Additional navigation items added
- Active page highlighted in nav
- Note, mobile nav functionality will be added via different ticket as it does not exist today
**Testing**
- Navigation design should match that seen on https://cop.prototype.cop.homeoffice.gov.uk/blue/sprint-34/tasks-team-v0-0
- Navigation items should be in the order seen on the prototype above
- Navigation items should link to
- - Home: /dashboard
- - Tasks /your-tasks
- - Forms /forms
- - Cases /cases
- - Reports /reports
- - My profile /submit-a-form/edit-your-profile
- - Support https://support.cop.homeoffice.gov.uk/servicedesk/customer/portal/3 
- Support should open in a new tab
- Sign out should sign you out
=> COP-1163 Update navigation

app/core/components/Header.jsx, app/core/components/Header.scss, app/core/components/__snapshots__/Header.test.js.snap, public/styles/app.scss
**AC**
- enable mobile nav show/hide nav links
- mobile links should be shown on the left below the service name
- onclick of link, menu should auto close
- service name should retain it's margins on mobile, even without GOV.UK logo
**Testing**
- open COP
- switch to a mobile width view
> you should see the 'menu' button rather than the nav links
- click on menu
- you should see the nav links on the left
- click on Tasks
> the menu should close & you should see your Tasks page
- switch to a desktop width view
> you should see the nav links once again
=> COP-1423 Mobile navigation updates

app/core/Main.jsx, app/core/components/Header.jsx, app/pages/cases/components/CaseResultsPanel.jsx, app/pages/cases/components/CaseResultsPanel.test.jsx, app/pages/cases/components/CasesPage.jsx
**AC**
Based on https://cop.prototype.cop.homeoffice.gov.uk/blue/sprint-34/case-overview?nginxId=a9c445dc-30d4-4df8-cd75-68b9fb259576
- setup 1/4 + 3/4 page structure
- add search panel
- add search result panel
- add search button functionality
----
**To test**
- go to /cases page
- enter a known businessKey
> you should see the search result list
- click on the link for the businessKey
> you should see the case (with it's current design) on the right panel
- try to enter a search query and click the search button before the automatic search kicks in
> you should see the search result list
=> COP-1188 Case view search

app/pages/tasks/components/SortTasks.jsx, app/pages/tasks/components/YourGroupTasks.test.jsx, app/pages/tasks/components/YourGroupTasksContainer.jsx, app/pages/tasks/components/YourTasks.test.jsx, app/pages/tasks/components/YourTasksContainer.jsx, app/pages/tasks/epic.js, app/pages/tasks/reducer.js, app/pages/tasks/reducer.test.js
**AC**
The default sort order for lists of tasks should be by oldest due date (`sort=due,asc`)
**TO TEST**
- login to COP
- go to Team Tasks
> you should see the sort dropdown as `Oldest due date`
> you should see the 'overdue' column indicating the oldest due tasks are first e.g. `Overdue 12 hours ago` should be above `Overdue 2 hours ago`
- Change the sort dropdown to `Latest due date`
> you should see the order change and now `Overdue 2 hours ago` should be above `Overdue 12 hours ago`
- go to Your Tasks
> you should see the sort dropdown as `Oldest due date`
> you should see the 'overdue' column indicating the oldest due tasks are first e.g. `Overdue 12 hours ago` should be above `Overdue 2 hours ago`
- Change the sort dropdown to `Latest due date`
> you should see the order change …
=> COP-1407 Update default sort order for tasks to be by oldest due date

app/common/AppConstants.js, app/pages/reports/components/PowerBIReport.jsx, app/pages/reports/components/PowerBIReport.test.jsx, app/pages/reports/components/ReportPage.jsx, app/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap, package-lock.json, package.json
For any window width lower than 500px we instead request the mobile report layout, if available, and change the iframe height. If one is not available, the main ("Master") one will load. This looks good in testing for me, but will ask Jade to check, too.
=> Request mobile layout of Power BI reports when suitable

app/common/AppConstants.js, app/core/util/priority.js, app/pages/task/display/component/TaskTitle.jsx, app/pages/tasks/components/TaskUtils.js, app/pages/tasks/components/TaskUtils.test.js, app/pages/tasks/components/YourGroupTasks.jsx
**AC**
There is a bug that prevents some tasks from showing when you group by Priority in tasklist
**Updated**
* assignment of High, Medium, Low based on bandings
* change default priority when no priority value is available to {{Medium}}
**Notes**
* BPMN's will be updated to use 50/100/150
* It's confirmed the guide documents use 50/100/150
* Anything to do with changes to BPMNs is not addressed in this PR
* Tasks without a specific priority set in the user task element of the BPMN are being created with a priority value of 50. This will be investigated in https://support.cop.homeoffice.gov.uk/browse/COP-256
**To test**
* Create an Events at the Border task
* Create an Intel Referral task and choose `Time constraint: yes`
* Create an Intel Referral task and choose `Time constraint: no`
* …
=> COP-1407 Assign priorities and group

app/common/security/SecureLocalStorage.js, app/pages/tasks/components/SortTasks.jsx, app/pages/tasks/components/YourGroupTasksContainer.jsx, app/pages/tasks/components/YourTasksContainer.jsx
**AC**
When a user selects a sort order and refreshes or leaves the page and returns, the sort order should persist.
This is for both My Tasks and My Group Tasks
**To Test**
- log into COP
- go to Your Tasks
- select sort by 'Highest Priority'
- refresh page
> your sort order should remain as Highest Priority
- go back to Dashboard
- go to Your Tasks again
> your sort order should remain as Highest Priority
Repeat the above for Your Group Tasks
=> COP-1803 Persist sort order

app/pages/forms/start/reducer.js
The issue is that after a user onboards a blank screen is displayed to the user instead a page notifying the user that they have onboarded successfully and the next steps they need to take.
This change fixes that by reverting commit 800363bbcf25d954b560a80d29ac55a7fd33ef71.
By reverting this commit we will fix the issue quickly and will have longer to find out why the change caused the issue before adding it back again.
=> Fix blank page being displayed after onboarding

Dockerfile.multi-stage
Both versions are multi-stage now, the new Dockerfile.multi-stage provides different
targets but will break original deployment method - so split into its
own seperate file.
modified:   Dockerfile
new file:   Dockerfile.multi-stage
=> Image-reduction multi stage build using alpine base image.

package-lock.json, package.json
Update `formio-gds-templates` version.
This update includes accessibility improvements for missing field labels.
Also associates labels with fields correctly using `id` and `for` attributes.
=> COP-1353 - Line manager details in Edit profile does not get read by screen reader

app/pages/tasks/components/GroupTasks.jsx, app/pages/tasks/components/TaskUtils.js, app/pages/tasks/components/YourGroupTasks.jsx
Allow the user to group tasks by assignee
- Added option of "Assignee" on "Group by" for tasks
- If a task has a null assignee, 'Unassigned' is rendered as opposed to 'null'
- Business key is used as the caption for each item within each group
- Create 2 Event at the Border tasks (does not matter what type)
- Claim one of the tasks (do not proceed to fill out form, return to dashboard)
- Open your group task list
- Group by 'Assignee'
- You should see <your@email> 1 task as one group
- You should see Unassigned 1 task as another separate group
=> Add group by assignee functionality for group task list

app/pages/cases/case-actions/components/CaseAction.jsx
User should not be able to submit multiple Stop SLA forms for one case.
- Updated `CaseAction.jsx` to fetch for the most up-to-date case 5 seconds after a case action form has been submitted (within the same `setTimeout` as the code that removes the case action response message).
- Instead of rendering null if `actionResponse` is false, it renders the case action form. 
- `actionResponse` is only ever truthy when a successful form submission has taken place and only the successful submission message is rendered without the form.
- If the form submission fails - the form will persist without requiring the user to refresh the page.
- The changes now prevent any case action form from being submitted after a user has just submitted a case form successfully - not just Stop SLA
*Scenario 1:*
- …
=> COP-1219 Prevent form rendering in case actions immediately after submission

app/pages/task/form/components/TaskForm.jsx, app/pages/task/form/components/TaskForm.test.jsx, app/pages/task/form/components/__snapshots__/TaskForm.test.jsx.snap
Add groups from the user's token to `keycloakContext` in `TaskForm` so it's available to the task forms
This will be used in the E@B people form so we can populate the IS81 groups dropdown box with the data that we already have in the token and therefore removes the need to do an additional API call to get these values.
Also by not calling the Keycloak API we no longer have the permissions issue of trying to call the API from the UI.
=> Add groups to keycloakContext in TaskForm so it's available to the task forms

app/core/shift/OnboardChecker.js, app/core/shift/OnboardChecker.test.js, app/index.jsx
COP has an API call to get the staff id from the staff details based on the user's email address. This works fine for existing users but new users don't have staff details saved in the db.
The issue with this is that the code is not checking if data is returned from the response before trying to return the staff id and throwing an error for a new user because it's trying to return `staffid` of an undefined value.
This change fixes that by checking if data is returned in the API response before trying to return `staffid` and if not then returning null.
Also updated the unit tests.
=> Check data is returned in the response from the staff details API call before trying to return the staff id

app/core/shift/withShiftCheck.jsx, app/index.jsx, app/pages/cases/case-actions/components/CaseAction.jsx, app/pages/dashboard/components/DashboardTitle.jsx, app/pages/forms/start/components/FormsStartPage.jsx, app/pages/forms/start/components/StartForm.jsx, app/pages/reports/components/PowerBIReport.jsx, app/pages/reports/components/PowerBIReport.test.jsx, app/pages/shift/components/ShiftForm.jsx, app/pages/shift/components/ShiftPage.jsx, app/pages/task/form/components/CompleteTaskForm.jsx, app/pages/task/form/components/TaskForm.jsx
In the case that multiple users are using the same browser we would not want them to retrieve or preload each other's data.
=> Make local storage keys user-specific

public/styles/app.scss
Change CSS rule to be less specific so it applies to textareas with other names than 'details'
=> COP-5143 - Change CSS rule to be less specific

app/pages/forms/start/components/FormsStartPage.jsx, app/pages/forms/start/components/FormsStartPage.test.jsx, app/pages/forms/start/components/StartForm.jsx, app/pages/forms/start/components/__snapshots__/FormsStartPage.test.jsx.snap, app/pages/task/form/components/TaskForm.jsx, app/pages/task/form/components/TaskForm.test.jsx, app/pages/task/form/components/__snapshots__/TaskForm.test.jsx.snap
In UI1 here, unlike in UI2, the user's roles are not currently added to the `keycloakContext` object. We want them be, however, so that we can check them for conditional validation in the COVID Compliance Checks form.
This PR accordingly grabs the `roles` array from the `tokenParsed.realm_access` object and adds it to the `keycloakContext` object. Note that both the `realm_access` object and the `roles` array are expected to be present (in PropTypes).
=> Make roles available on keycloakContext object

app/pages/forms/start/components/StartForm.jsx, app/pages/shift/components/ShiftForm.jsx, app/pages/task/form/components/TaskForm.jsx, app/pages/task/form/components/__snapshots__/TaskForm.test.jsx.snap
If we try to perform validation that depends on certain context objects which are removed when the form is submitted, we run into a problem when the `beforeSubmit` hook is used in that they are removed before the validation occurs. If we instead use the `customValidation` hook then these objects are removed _after_ validation occurs, getting around the problem.
=> Use customValidation instead of beforeSubmit hook

app/pages/cases/case-actions/components/CaseAction.jsx, app/pages/cases/case-actions/components/CaseAction.test.jsx, app/pages/cases/case-actions/components/CaseActions.test.jsx
In Operating Mandate we need to be able to pre-populate the initial request form in the Case Actions in Case View with the latest data so that the user can add additional information to the request.
This change does that by adding a `latestFormDataPath()` method which gets the latest form data path, which is the file path of the data in the S3 bucket, and if this exists the it is used to fetch the data. This method is called when the component mounts and when it updates to ensure that we load the data if necessary when the first tab loads and when subsequent tabs are selected.
The data is only pre-populated in the form if the field `calculatedValue` uses the new `formSubmissionData` object to set the field value, for example `value = data.formSubmissionData.fieldApiKey` so forms won't get …
=> Cop 6739 operating mandate append record

app/pages/cases/case-actions/components/CaseAction.jsx, app/pages/cases/case-actions/components/CaseActions.jsx, app/pages/cases/components/CaseDetailsPanel.jsx
These changes improve the append a record functionality that is used in Case View for Operating Mandate.
1. Update CaseAction to prepopulate the form if the form has a flag set. We're now setting a flag in the form to determine if the Case Action is prepopulated rather than relying on the data being available in `data.formSubmissionData` as the latter was proving too unreliable.
2.  Update CaseActions to close the form view if a Case Action tab is selected. We need to ensure that we don;t have cross-contamination of the data in the forms in the Case Action and the form view below so when the Case Action tab is selected the form below is reset.
3.  Update CaseDetailsPanel to reset the Case Action tab if a form view is opened. Similarly to above, we want to avoid cross-contamination of the …
=> COP-6739 - Operating Mandate Append Record
