- app/config.js
- app/core/shift/epic.js
- app/pages/dashboard/epic.js
- app/pages/messages/epic.js
- app/pages/procedures/list/epic.js
- app/pages/procedures/start/epic.js
- app/pages/reports/components/ReportPage.jsx
- app/pages/reports/components/ReportPage.test.js
- app/pages/reports/epic.js
- app/pages/task/display/component/Comments.jsx
- app/pages/task/display/epic.js
- app/pages/task/form/epic.js
- app/pages/tasks/epic.js
Update service urls so they now point to the correct service instead of being proxied
> Update service urls

- app/config.js
- app/pages/dashboard/components/DashboardPanel.jsx
- app/pages/procedures/diagram/epic.js
- app/pages/task/form/epic.js
- app/pages/tasks/components/YourTasksContainer.js
- kube/deployment.yml
Added deployment env vars
Removed `://` from urls as this is included in `PROTOCOL` env var
> Update service hostnames

- app/core/shift/epic.js
- app/core/shift/epic.test.js
- app/index.js
- app/pages/dashboard/components/DashboardPanel.jsx
- app/pages/dashboard/epic.js
- app/pages/messages/epic.js
- app/pages/messages/epic.test.js
- app/pages/procedures/diagram/epic.js
- app/pages/procedures/list/epic.js
- app/pages/procedures/start/epic.js
- app/pages/reports/components/ReportPage.jsx
- app/pages/reports/components/ReportPage.test.js
- app/pages/reports/epic.js
- app/pages/reports/epic.test.js
- app/pages/task/display/component/Comments.jsx
- app/pages/task/display/component/TaskDetailsPage.test.js
- app/pages/task/display/epic.js
- app/pages/task/form/epic.js
- app/pages/tasks/components/YourTasksContainer.js
- app/pages/tasks/epic.js
- server.js
Pass env vars into the UI and reference them correctly in the URLs
> Pass env vars into the UI and reference them correctly in the URLs

- app/config.js
Export config with module.exports instead of export default
> Export config with module.exports instead of export default

- kube/deployment.yml
Add env vars to deployment.yml
> Add env vars to deployment.yml

- package-lock.json
- package.json
This version includes the bug fix for dropdown box ajax headers not being sent
> Upgrade formiojs to 4.0.0-beta.37

- app/pages/task/display/component/Comments.jsx
Add appConfig into props validation
> Add appConfig into props validation

- public/styles/app.scss
> Add styling for datagrid label, dropdown box and remove button

- app/core/components/UnauthorizedPage.jsx
- app/core/components/UnauthorizedPage.test.js
- Fix linting errors
- Change unauthorized error message
> CO-165 - Amend the COP error message when a user is not in AD and tries to log into COP

- app/core/components/Header.jsx
- public/styles/app.scss
Add support link to the header
Fix linting errors that already existed in Header.jsx
> Add support link

- .drone.yml
> missed removing cert from deploy

- app/pages/procedures/start/components/ProcedureStartPage.jsx
- app/pages/task/form/components/CompleteTaskForm.jsx
Make sure the formio cache is cleared after submitting the form
This will ensure that when a new form is loaded, it gets loaded with fresh data
> Make sure the formio cache is cleared after submitting the form

- app/pages/task/form/components/CompleteTaskForm.jsx
Add missing import statement in CompleteTaskForm.jsx
> Add missing import statement in CompleteTaskForm.jsx

- app/pages/procedures/start/epic.js
- app/pages/task/form/epic.js
> Revert "Repoint engine form data submission to translation service"

- package-lock.json
- package.json
Attempt to fix build pipeline transpilation issue.
> Add transform-object-rest-spread dependency

- .babelrc
Last attempt didn't fix transpilation, but this should.
> Fix object-spread issue

- app/pages/dashboard/components/CalendarDashboardPanel.jsx
- app/pages/dashboard/components/CalendarDashboardPanel.test.js
- app/pages/dashboard/components/ProceduresDashboardPanel.jsx
- app/pages/dashboard/components/ReportsDashboardPanel.jsx
- app/pages/dashboard/components/ReportsDashboardPanel.test.js
- app/pages/dashboard/components/__snapshots__/CalendarDashboardPanel.test.js.snap
- app/pages/dashboard/components/__snapshots__/ProceduresDashboardPanel.test.js.snap
- app/pages/dashboard/components/__snapshots__/ReportsDashboardPanel.test.js.snap
Remove links from Reports and Calendar dashboard panels and change dashboard text
> Remove links from Reports and Calendar dashboard panels

- app/pages/dashboard/components/DashboardPanel.jsx
Noticed this issue in logs when running in Dev mode.
> Correct scope of props lookup

- app/pages/task/display/component/TaskTitle.jsx
- package.json
This PR ensures that when actioning a task assigned to you (as a user) instead of seeing the "Due" time in UTC Time it will now be shown to the user in Local Time.
To test, click on "Tasks assigned to you" button in the Dashboard, and then click on the "Action" button for a task and you will see the new "Due" time being displayed in Local Time.
Run tests:
`npm test`
Run linter (this command runs linter for the `TaskTitle` module only):
`npm run linter:dev -- app/pages/task/display/component/TaskTitle.jsx`
> Update Task UTC Time to Local Time

- .drone.yml
- README.md
- env.yaml
- Use named kubenamespace variable
- Synch staging and production secrets on push to master
- Updated readme with env variable list and values
- Use protocol constant variable
> CB-712 Repository improvements

- .eslintrc.json
- app/pages/task/display/component/TaskSummaryPage.jsx
- app/pages/task/display/component/TaskTitle.jsx
- app/pages/tasks/components/YourGroupTasks.jsx
This PR refactors components as stateless components, it also ensures that instead of passing all the props into a component we only pass the props that the component needs.
Linting.
Run linter (this command runs linter for the TaskTitle module only):
```
npm run linter:dev -- <component_path>/<module_name>.jsx
```
> Refactor tasks components

- package-lock.json
- package.json
This reverts commit 8d6050a995a231f20ea29a802b30485419c9d15d.
> Revert "bump version to latest formio"

- app/pages/task/display/component/Claim.jsx
This PR reverts back the prop types declaration for the time being in order to fix a bug on dev
> Revert back prop types declaration

- app/pages/tasks/components/YourGroupTasks.jsx
- app/pages/tasks/components/YourGroupTasksContainer.js
- app/pages/tasks/components/YourTasks.jsx
- app/pages/tasks/components/YourTasksContainer.js
This PR removes unnecessary 'Submit a form' hyperlinks from 'Your tasks' and 'Your group tasks' pages
To run linter execute:
```
npm run linter:dev -- app/pages/tasks/components/YourTasks.jsx
npm run linter:dev -- app/pages/tasks/components/YourGroupTasks.jsx
```
> Remove unnecessary submit form hyperlink

- app/index.jsx
[JIRA ticket](https://support.cop.homeoffice.gov.uk/browse/CB-850)
> Remove authorized role check

- app/pages/procedures/list/components/ProceduresPage.jsx
- app/pages/procedures/list/components/ProceduresPage.test.js
This PR removes the 'View procedure' hyperlink when viewing the forms page.
> Remove view procedures hyperlink

- app/pages/task/display/component/Audit.jsx
This PR updates the Audit component to a stateless component, and lints module.
Run linter (this command runs linter for the Audit module only):
```
npm run linter:dev -- app/pages/task/display/component/Audit.jsx
```
> Updates Audit component to stateless component

- package-lock.json
- package.json
Fixes for edit grid / Datagrid
> bump digital patterns and react-formio deps

- package-lock.json
- package.json
A package was deleted from the `package.json` while still being required by the Dev config, meaning the Dev build could no longer compile following a fresh `npm install`.
> Fix Webpack Dev build

- package-lock.json
- package.json
- webpack.dev.js
This PR removes unused package and remove its import dependencies.
> Remove unused package

- .eslintrc.json
- app/pages/task/display/component/Claim.jsx
This PR updates the Claim component methods, adds props validation and lints the module.
Run linter (this command runs linter for the Claim module only):
```
npm run linter:dev -- app/pages/task/display/component/Claim.jsx
```
> Update claim component

- app/pages/forms/start/components/FormsStartPage.jsx
- app/pages/forms/start/components/__snapshots__/FormsStartPage.test.js.snap
This PR fixes "Back to forms" link, when viewing a form.
To run tests:
```
npm test
```
> Fix back to forms link

- app/pages/dashboard/components/DashboardTitle.jsx
This PR updates the style of the 'End shift' button to warning.
> Update end shift button style

- app/config/core.js
- app/core/App.jsx
- app/core/components/Footer.jsx
- app/core/components/Header.jsx
- app/core/components/__snapshots__/Header.test.js.snap
This PR:
* remove environment banner when in production,
* add service desk feedback link,
* move hard-coded service desk into configuration,
> Update phase banner

- app/pages/dashboard/components/NoOpDashboardPage.jsx
Change the text on the onboarding confirmation page
> CO-1210 - Onboard confirmation page

- app/core/components/AccessibilityStatement.jsx
- app/core/components/__snapshots__/AccessibilityStatement.test.jsx.snap
A couple of amendments after feedback from Kevin.
> Accessibility Statement - amendments

- app/core/error/component/ErrorHandlingComponent.jsx
- app/core/error/component/FormErrorPanel.jsx
- app/core/util/FormioEventListener.js
- package-lock.json
- package.json
> Fix error handler

- app/pages/shift/components/ShiftForm.jsx
Check that the default team exists before using it
> CO-1258 - Shift changes

- .eslintrc.json
- app/core/components/Header.jsx
- app/core/components/SkipLink.jsx
- app/core/components/SkipLink.test.jsx
- app/core/components/__snapshots__/Header.test.js.snap
- app/core/util/scrollToMainContent.js
- app/core/util/scrollToMainContent.test.js
Adds GDS skip link functionality inside header. 100% test coverage included.
> Add SkipLink functionality

- app/pages/cases/components/CasesPage.jsx
- app/pages/dashboard/components/TaskCountPanel.jsx
- app/pages/forms/list/components/FormsListPage.jsx
- app/pages/forms/list/components/FormsListPage.test.jsx
- app/pages/forms/start/components/FormsStartPage.jsx
- app/pages/forms/start/components/__snapshots__/FormsStartPage.test.jsx.snap
- app/pages/messages/components/MessagesPage.jsx
- app/pages/messages/components/MessagesPage.test.jsx
- app/pages/reports/components/ReportsPage.jsx
- app/pages/reports/components/ReportsPage.test.jsx
- app/pages/task/display/component/TaskPage.jsx
- app/pages/task/display/component/TaskTitle.jsx
- app/pages/task/form/components/TaskForm.jsx
- app/pages/tasks/components/YourGroupTasks.jsx
- app/pages/tasks/components/YourGroupTasks.test.jsx
- app/pages/tasks/components/YourGroupTasksContainer.js
- app/pages/tasks/components/YourTasks.jsx
- app/pages/tasks/components/YourTasks.test.jsx
This PR adds grey headings to Your Tasks, Your Group's Tasks and Case View pages and tweaks document titles and tests to match.
It also changes word "allocated" to "assigned" for consistency, and the second commit fixes various minor linting issues.
> Add grey headings to COP pages - etc.

- .drone.yml
- env.yaml
Temporary whilst we collect information
> CB-1391 Integration with Service Now Databuild environment

- server.js
New env vars also need adding to this file to be provided to the UI.
> Add env vars to server config

- package-lock.json
This release includes my fixes for shift team menu and OAR disabled input validation.
> Bump formiojs to v4.9.19

- app/pages/cases/components/CasesPage.jsx
Updating prefix to say "COP" and tweaking instruction slightly.
> Amend placeholder text and instruction

- public/index.html
- webpack.common.js
- webpack.prod.js
Edge is stubborn! This seems to make it update.
> Manually link to new favicon with force refresh

- package-lock.json
This enables the app to build on node 14.
> Upgrade node-sass bindings

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/Header.scss
> COP-1163 Navigation

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/Header.test.js
- app/core/components/__snapshots__/Header.test.js.snap
- app/pages/forms/list/components/FormsListPage.jsx
- app/pages/forms/list/components/FormsListPage.test.jsx
- public/styles/app.scss
Additional updates
**Persist active menu design when subpage viewed**
_Split the style menu function (setActiveNavItem) out from the onClick function (handleLinkClick) so that they style can be set at page load_
- go to Forms
- click on a form
>Forms in menu should remain coloured blue
**Default body font size should be 19px**
_Set the font-size of app-container to be 19px so that rem/em sizing is taken from that rather from the browser default of 16px_
- go to Forms
>the font size of the links should be 19px
**Update supporting text**
New text provided by Abedul
> COP-1187 Form list design updates

- app/pages/dashboard/components/CasesDashboardPanel.jsx
CasesDashboardPanel had references to Calendar - updated to Cases
> Fix CasesDashboardPanel so it references Cases and not Calendar

- app/pages/dashboard/components/CasesDashboardPanel.jsx
- app/pages/dashboard/components/FormsDashboardPanel.jsx
- app/pages/dashboard/components/MessagesPanel.jsx
- app/pages/dashboard/components/ReportsDashboardPanel.jsx
- app/pages/dashboard/components/TaskCountPanel.jsx
- app/pages/dashboard/components/__snapshots__/FormsDashboardPanel.test.js.snap
- app/pages/dashboard/components/__snapshots__/ReportsDashboardPanel.test.js.snap
- public/styles/homeoffice.scss
Revert link styling for dashboard panels back to GDS classes/colours
> COP-1164 Dashboard design - revert to GDS links

- app/pages/reports/components/PowerBIReport.jsx
- app/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap
Quick one to hide the filter pane for embedded reports as per Richard's request.
> Hide filter pane

- app/pages/reports/components/ReportPage.jsx
Enable iframe to show optimally on narrow or wide screens.
> Fix report size

- app/core/components/Header.jsx
- app/core/components/Header.test.js
- app/core/components/__snapshots__/Header.test.js.snap
- public/styles/app.scss
**AC**
Navigation should show as active colour if the related dashboard link is clicked to take you to that page
**Testing**
- go to /dashboard
- click Forms on the dashboard
> You should see the Form nav item highlighted in blue
- go to Home
> You should see the Home nav item highlighted in blue
> COP-1164 Navigation active nav styling

- app/core/components/Header.jsx
- app/core/components/Header.test.js
- app/core/components/__snapshots__/Header.test.js.snap
- public/styles/app.scss
Reverts UKHomeOffice/cop-private-workflow-tasklist#309
> Revert "COP-1164 Navigation active nav styling"

- app/pages/dashboard/components/CasesDashboardPanel.jsx
- app/pages/dashboard/components/FormsDashboardPanel.jsx
- app/pages/dashboard/components/MessagesPanel.jsx
- app/pages/dashboard/components/ReportsDashboardPanel.jsx
- app/pages/dashboard/components/TaskCountPanel.jsx
- app/pages/dashboard/components/__snapshots__/FormsDashboardPanel.test.js.snap
- app/pages/dashboard/components/__snapshots__/ReportsDashboardPanel.test.js.snap
- public/styles/homeoffice.scss
Reverts UKHomeOffice/cop-private-workflow-tasklist#305
> Revert "COP-1164 Dashboard design - revert to GDS links"

- app/pages/dashboard/components/CasesDashboardPanel.jsx
Reverts UKHomeOffice/cop-private-workflow-tasklist#302
> Revert "Fix CasesDashboardPanel so it references Cases and not Calendar"

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/Header.test.js
- app/core/components/__snapshots__/Header.test.js.snap
- app/pages/forms/list/components/FormsListPage.jsx
- app/pages/forms/list/components/FormsListPage.test.jsx
- public/styles/app.scss
Reverts UKHomeOffice/cop-private-workflow-tasklist#301
> Revert "COP-1187 Form list design updates"

- app/core/components/Header.jsx
- app/core/components/Header.scss
- app/core/components/__snapshots__/Header.test.js.snap
- public/styles/app.scss
Reverts UKHomeOffice/cop-private-workflow-tasklist#299
> Revert "COP-1423 Mobile navigation updates"

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/__snapshots__/Header.test.js.snap
Reverts UKHomeOffice/cop-private-workflow-tasklist#298
> Revert "Update links and snapshot"

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/Header.scss
Reverts UKHomeOffice/cop-private-workflow-tasklist#297
> Revert "COP-1163 Navigation"

- app/common/AppConstants.js
- app/core/components/Header.jsx
- app/core/components/Header.scss
- app/core/components/Header.test.js
- app/core/components/__snapshots__/Header.test.js.snap
Reverts UKHomeOffice/cop-private-workflow-tasklist#296
> Revert "COP-1163 Update navigation"

- app/core/components/LogoBar.jsx
- app/core/components/LogoBar.scss
- app/core/components/LogoBar.test.jsx
- app/core/components/__snapshots__/LogoBar.test.jsx.snap
- app/pages/reports/components/PowerBIReport.jsx
- app/pages/reports/components/ReportPage.jsx
- app/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap
This is for Michael B to see. It can always be changed/enhanced from here, especially when we come to consider mobile view.
> Add full screen functionality and refresh instruction under PBI reports

- app/common/TaskPriorityConstants.js
- app/core/util/priority.js
- app/pages/task/display/component/TaskDetailsPage.test.js
- app/pages/task/display/component/TaskTitle.jsx
- app/pages/tasks/components/TaskUtils.js
- app/pages/tasks/components/TaskUtils.test.js
Reverts UKHomeOffice/cop-private-workflow-tasklist#326
Investigating why works locally but not on dev - reverting for now so Dev isn't broken
> Revert "COP-1407 Grouping by priority"

- app/pages/tasks/components/YourTasks.jsx
Same as we did for group tasks
> Replicate hiding h3 when 0 tasks in a group

- .drone.yml
- app/index.jsx
- app/pages/reports/components/ReportsPage.jsx
- app/pages/reports/components/ReportsPage.test.jsx
- app/pages/reports/selectors.js
- app/pages/reports/selectors.test.js
- env.yaml
- kube/deployment.yml
- webpack.dev.js
> Add link to Product Page reports guidance

- app/core/error/reducer.js
- app/core/shift/extendedStaff.reducer.js
- app/core/shift/shift.reducer.js
- app/pages/cases/reducer.js
- app/pages/dashboard/reducer.js
- app/pages/forms/diagram/reducer.js
- app/pages/forms/list/reducer.js
- app/pages/forms/start/reducer.js
- app/pages/messages/reducer.js
This fixes this rule across the codebase and brings the number of remaining issues down to 53.
> Fix no-case-declarations

- app/pages/reports/components/ReportsPage.jsx
Updated as per [GDS guidance](https://design-system.service.gov.uk/styles/typography/#links).
> Update link text

- .eslintrc.json
- app/pages/cases/components/FormDetailsPanel.jsx
**Bug**
- Open COP and navigate to Case View
- Load up a case
- Expand all of the sections
- Click "show detail" on one of the forms
- Click "show detail" on a different form
**Notes**
In `componentDidUpdate` - `(this.props.formVersionDetails && this.formNode.element)` was often resulting in `TypeError: Cannot read property 'element' of null`
> COP-1694 Fix bug where page displays no content

- app/pages/reports/components/PowerBIReport.jsx
- app/pages/reports/components/PowerBIReport.test.jsx
- app/pages/reports/components/ReportPage.jsx
- app/pages/reports/components/ReportPage.test.jsx
- app/pages/reports/components/__snapshots__/PowerBIReport.test.jsx.snap
- package.json
There is some hard coding in here which we would like to avoid in future but this is stable enough to into production after testing. We plan to revisit the approach and see if we can make it more dynamic when we have additional Power BI reports to handle.
> Pre-select user's branch in Command Brief report

- app/core/components/AccessibilityStatement.jsx
- app/core/components/__snapshots__/AccessibilityStatement.test.jsx.snap
> Further updates to Accessibility Statement

- app/index.jsx
• Omit staff details if no copge role found
• Only fetch team if teamid found
> Handle users not onboarded

- app/index.jsx
> Add firstname and surname to staffDetails

- app/pages/forms/start/components/StartForm.jsx
So that they can be displayed in User Profile form.
> Add groups to keycloakContext object

- app/core/components/AccessibilityStatement.jsx
- app/core/components/__snapshots__/AccessibilityStatement.test.jsx.snap
> Rename EU Transition form to be Record Trade Checks

- app/core/components/PrivacyAndCookiePolicy.jsx
- app/core/components/__snapshots__/PrivacyAndCookiePolicy.test.jsx.snap
Various updates as per Word document and some further tweaks for consistency.
> Update Privacy Policy

- app/index.jsx
- package-lock.json
- package.json
A new version of this package been published; it'll be consistent if all our UIs use this.
> Use Home Office GDS templates

- app/pages/cases/components/CaseAttachments.jsx
fix for - "uploaded on" time one hour behind
> COP-6436 EaB Case View Attachments

- app/core/components/Footer.jsx
- app/core/components/Header.jsx
- app/core/components/__snapshots__/Header.test.jsx.snap
> Align support links with GDS recommendations
